[phases.setup]
nixPkgs = ["python311", "gcc", "pango", "cairo", "gdk-pixbuf", "libffi", "zlib", "fontconfig", "freetype"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]
